import React,{useEffect,useRef,useState} from 'react';
import {motion,useMotionValue} from 'motion/react';
import {Liquid} from 'liquid-gooey';
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
export function FloatingControls({plain}){
 const stage=document.querySelector('.stage');
 const x=useMotionValue(Math.max(12,stage.clientWidth-68)),y=useMotionValue(Math.max(12,stage.clientHeight-68));
 const [open,setOpen]=useState(false),[edges,setEdges]=useState({left:false,top:false});
 const gesture=useRef(null),suppress=useRef(0),root=useRef(null),edgeRef=useRef(edges);
 const wasOpen=useRef(false);useEffect(()=>{if(wasOpen.current&&!open&&root.current?.contains(document.activeElement)&&!document.activeElement.classList.contains('menu-toggle'))root.current.querySelector('.menu-toggle').focus({preventScroll:true});wasOpen.current=open;},[open]);
 const publish=()=>{const p={x:x.get(),y:y.get(),left:x.get()+28<stage.clientWidth/2,top:y.get()+28<stage.clientHeight/2,width:stage.clientWidth,height:stage.clientHeight};if(p.left!==edgeRef.current.left||p.top!==edgeRef.current.top){edgeRef.current={left:p.left,top:p.top};setEdges(edgeRef.current);}stage.dataset.dockSide=p.left?'left':'right';document.dispatchEvent(new CustomEvent('dock-position',{detail:p}));};
 const move=(nx,ny)=>{x.set(clamp(nx,12,Math.max(12,stage.clientWidth-68)));let safeY=clamp(ny,86,Math.max(86,stage.clientHeight-76));const bar=document.querySelector('#dockEffects>.statebar')?.getBoundingClientRect();if(bar&&x.get()<bar.right+8&&x.get()+56>bar.left-8&&safeY+56>bar.top-8)safeY=Math.max(86,bar.top-64);y.set(safeY);publish();};
 const end=cancel=>{const d=gesture.current;gesture.current=null;if(d&&root.current.hasPointerCapture(d.id))root.current.releasePointerCapture(d.id);if(d?.moved){suppress.current=performance.now()+500;if(cancel)move(d.startX,d.startY);} };
 useEffect(()=>{const close=()=>setOpen(false),key=e=>{if(e.key==='Escape'){close();end(true);}};const resize=()=>{end(true);move(x.get(),y.get());};const observer=new ResizeObserver(resize);observer.observe(stage);document.addEventListener('keydown',key);document.getElementById('viewport').addEventListener('pointerdown',close);publish();return()=>{observer.disconnect();document.removeEventListener('keydown',key);document.getElementById('viewport').removeEventListener('pointerdown',close);};},[]);
 const sx=edges.left?1:-1,sy=edges.top?1:-1;
 const actions=[{id:'process',label:'Flow',x:120*sx,y:56*sy},{id:'stylesButton',label:'Style',controls:'stylesPanel',x:66*sx,y:110*sy},{id:'toolsButton',label:'Tools',controls:'toolsPanel',x:0,y:134*sy}];
 const pieces=<>{actions.map(({x:dx,y:dy,...a},i)=>{const tx=clamp(x.get()+dx,12,stage.clientWidth-68)-x.get(),ty=clamp(y.get()+dy,86,stage.clientHeight-76)-y.get();const child=<button id={a.id} aria-label={a.id==='process'?'Animate gas flow':a.label} aria-controls={a.controls} aria-expanded={a.controls?false:undefined} aria-pressed={a.id==='process'?false:undefined} tabIndex={open?0:-1} style={{opacity:open?1:0,pointerEvents:open?'auto':'none'}} onClick={()=>setOpen(false)}>{a.label}</button>;return plain?<div key={a.id} className="menu-item" style={{transform:`translate(${open?tx:0}px,${open?ty:0}px)`}}>{child}</div>:<Liquid.Item key={a.id} className="menu-item" x={open?tx:0} y={open?ty:0} transition="bouncy" delay={open?i*25:0}>{child}</Liquid.Item>;})}<Main plain={plain}><button className="menu-toggle" aria-describedby="controlInstructions" aria-label={open?'Close controls':'Open controls'} aria-expanded={open} title="Tap to open · drag to move · arrow keys to reposition" style={{touchAction:'none'}}
 onPointerDown={e=>{if(!e.isPrimary){end(true);return;}if(e.button!==0)return;suppress.current=0;gesture.current={id:e.pointerId,px:e.clientX,py:e.clientY,startX:x.get(),startY:y.get(),moved:false};root.current.setPointerCapture(e.pointerId);}}
 onClick={e=>{if(e.detail!==0&&performance.now()<suppress.current)return;publish();setOpen(!open);}}
 onKeyDown={e=>{const delta={ArrowLeft:[-24,0],ArrowRight:[24,0],ArrowUp:[0,-24],ArrowDown:[0,24]}[e.key];if(delta){e.preventDefault();setOpen(false);move(x.get()+delta[0],y.get()+delta[1]);}}}><span style={{transform:`rotate(${open?45:0}deg)`}}>+</span></button></Main></>;
 return <motion.div ref={root} className="floating-gooey" style={{x,y}} onPointerMove={e=>{const d=gesture.current;if(!d||d.id!==e.pointerId)return;const dx=e.clientX-d.px,dy=e.clientY-d.py;if(!d.moved&&Math.hypot(dx,dy)<8)return;if(!d.moved){setOpen(false);root.current.setPointerCapture(e.pointerId);}d.moved=true;move(d.startX+dx,d.startY+dy);}}
 onPointerUp={e=>{if(gesture.current?.id!==e.pointerId)return;const tapped=!gesture.current.moved;end(false);if(tapped){publish();setOpen(current=>!current);suppress.current=performance.now()+500;}}}
 onPointerCancel={e=>{if(gesture.current?.id===e.pointerId)end(true);}}
 onLostPointerCapture={e=>{if(e.target===e.currentTarget&&gesture.current?.id===e.pointerId)end(true);}}>{plain?<div className="gooey-menu plain-menu">{pieces}</div>:<Liquid className="gooey-menu" blur={6} contrast={18} filterPadding={190} fill="#30383b" shadow="0 6px 18px rgba(0,0,0,.28), inset 0 1px 0 rgba(255,255,255,.12)">{pieces}</Liquid>}</motion.div>;
}
function Main({plain,children}){return plain?<div className="menu-item menu-main">{children}</div>:<Liquid.Item className="menu-item menu-main" radius={28}>{children}</Liquid.Item>;}
