import * as T from '../../../public/biogas/vendor/three.module.js';
import {OrbitControls} from '../../../public/biogas/vendor/OrbitControls.js';
const $=id=>document.getElementById(id),state={mode:'stopped',time:0,wire:false},reduced=matchMedia('(prefers-reduced-motion: reduce)');
const stage=$('stage'),scene=new T.Scene(),camera=new T.OrthographicCamera(-78,78,85,-85,.1,1000);let renderer;
try{renderer=new T.WebGLRenderer({antialias:true,alpha:true})}catch(e){$('loading').textContent='3D unavailable on this device. The isometric plate and transport controls remain usable.'}
const targets=[],moving=[],root=new T.Group();scene.add(root);
const metal=new T.MeshStandardMaterial({color:'#bfc4c5',metalness:.72,roughness:.36}),black=new T.MeshStandardMaterial({color:'#181c1d',roughness:.65}),white=new T.MeshStandardMaterial({color:'#dce0dd',metalness:.45,roughness:.4}),orange=new T.MeshStandardMaterial({color:'#f75935',roughness:.45});
function rounded(w,d,h,r){const s=new T.Shape(),x=-w/2,z=-d/2;s.moveTo(x+r,z);s.lineTo(x+w-r,z);s.quadraticCurveTo(x+w,z,x+w,z+r);s.lineTo(x+w,z+d-r);s.quadraticCurveTo(x+w,z+d,x+w-r,z+d);s.lineTo(x+r,z+d);s.quadraticCurveTo(x,z+d,x,z+d-r);s.lineTo(x,z+r);s.quadraticCurveTo(x,z,x+r,z);const bevel=Math.min(.5,h/4);const g=new T.ExtrudeGeometry(s,{depth:h-2*bevel,bevelEnabled:true,bevelThickness:bevel,bevelSize:bevel,bevelSegments:3,curveSegments:16});g.rotateX(-Math.PI/2);return g}
function obj(geometry,material,pos,name,description,action,parent=root){const o=new T.Mesh(geometry,material);o.position.set(...pos);o.userData={name,description,action};parent.add(o);targets.push(o);const lines=new T.LineSegments(new T.EdgesGeometry(geometry,25),new T.LineBasicMaterial({color:'#85918e',transparent:true,opacity:.5}));lines.visible=false;o.add(lines);o.userData.lines=lines;return o}
obj(rounded(68,96,15,3),metal,[0,0,0],'Aluminium housing','Published body envelope: 68 × 96 × 16 mm. Edge radii and recess depths are approximate.');
obj(rounded(66,94,.9,2.5),metal,[0,15,0],'Face plate','Rounded metal face with a central reel and recessed display.');
const wheel=new T.Group();wheel.position.set(0,16,-3);root.add(wheel);
obj(new T.CylinderGeometry(26.6,26.6,.8,96),black,[0,.1,0],'Reel surround','Dark recess around the motorised reel.',null,wheel);
obj(new T.CylinderGeometry(25.7,25.7,2,96),white,[0,1.2,0],'Motorised reel','Tap to pause or resume the simulated transport.','play',wheel);
for(const r of [8.2,16.5,24.8]){const o=obj(new T.TorusGeometry(r,.09,6,96),metal,[0,2.4,0],'Reel machined rings','Fine concentric detailing interpreted from reference photos.',null,wheel);o.rotation.x=Math.PI/2}
for(let i=0;i<6;i++){const a=i*Math.PI/3;const o=obj(rounded(3.2,7,.2,1.2),black,[Math.sin(a)*20.6,2.25,Math.cos(a)*20.6],'Reel index details','Repeated detailing on the reel surface; approximate.',null,wheel);o.rotation.y=a}
obj(new T.CylinderGeometry(3.2,3.2,.6,32),metal,[0,2.6,0],'Reel centre','Central spindle detail.',null,wheel);
const canvas=document.createElement('canvas');canvas.width=256;canvas.height=80;const screenTex=new T.CanvasTexture(canvas);screenTex.colorSpace=T.SRGBColorSpace;
obj(rounded(29,9,.6,1),black,[-6,16,-40],'Monochrome display','Live simulated transport state. The real device uses a 64 × 32 monochrome display.');
const screen=obj(new T.PlaneGeometry(26.5,7),new T.MeshBasicMaterial({map:screenTex}),[-6,16.7,-40],'Display surface','Shared state updates this display and the SVG plate.');screen.rotation.x=-Math.PI/2;
for(let i=0;i<7;i++)obj(new T.BoxGeometry(1, .25,4),i===0?orange:white,[14+i*1.9,16.3,-40],'Meter segments','Illustrative VU/indicator details. Values are not measured audio.');
function textTexture(label){const c=document.createElement('canvas');c.width=128;c.height=64;const g=c.getContext('2d');g.fillStyle='#dce0dd';g.fillRect(0,0,128,64);g.fillStyle='#171b19';g.font='32px monospace';g.textAlign='center';g.textBaseline='middle';g.fillText(label,64,32);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t}
for(const [x,key,glyph] of [[-20,'rec','●'],[0,'play','▶'],[20,'stop','■']]){const g=new T.Group();g.position.set(x,16,37);root.add(g);const cap=obj(rounded(15,10,2.2,1.5),key==='rec'?orange:white,[0,0,0],key+' transport','Press to change the simulated transport.',key,g);const top=obj(new T.PlaneGeometry(12,7),new T.MeshBasicMaterial({map:textTexture(glyph)}),[0,2.75,0],key+' key','Same handler as the labelled button.',key,g);top.rotation.x=-Math.PI/2;moving.push({key,g,y:16})}
for(const [x,label,key] of [[-28,'−','rew'],[28,'+','ff']]){const p=obj(new T.PlaneGeometry(5,5),new T.MeshBasicMaterial({map:textTexture(label)}),[x,16.2,23],label+' face control','Moves the simulated timeline five seconds.',key);p.rotation.x=-Math.PI/2}
// Side rocker, menu and memo controls, interpreted from product references.
obj(rounded(3,32,9,1),white,[-35,3,-2],'Left rocker','Upper/lower portions scrub the timeline. In this concept a tap advances five seconds.','ff');
obj(new T.BoxGeometry(2,6,8),black,[-35,7,27],'Menu button','Reference side-menu button; inspectable visual detail.');
obj(new T.BoxGeometry(2.5,7,12),white,[35,7,-14],'Memo button','Starts the simulated memo timer.','memo');
for(const z of [12,30])obj(new T.BoxGeometry(2,5,6),white,[35,7,z],'User button','Approximate side user control.');
for(let i=0;i<8;i++)obj(new T.BoxGeometry(.35,4,.8),black,[-34.6,6,34+i*.9],'Speaker grille','Repeated slots indicate the side speaker.');
// Three configurable top jacks, USB-C, and rotary power/volume control.
function jack(x,z,r,name){const tor=obj(new T.TorusGeometry(r,.55,10,32),metal,[x,8,z],name,'Connector representation. Ports are inert in this concept.');const hole=obj(new T.CircleGeometry(r-.45,32),black,[x,8,z+.08*Math.sign(z)],name+' recess','Dark socket recess.');if(z<0){tor.rotation.y=Math.PI;hole.rotation.y=Math.PI}}
for(const x of [-24,-11,2])jack(x,-48.6,2.6,'Two-way 3.5 mm jack');
const usb=obj(new T.BoxGeometry(8,3, .6),black,[16,8,-48.7],'USB-C','Reference data/power connector; no hardware connection.');
const power=obj(new T.CylinderGeometry(3.6,3.6,3,32),black,[28,8,-49.8],'Power / volume dial','Approximate top-edge dial.');power.rotation.x=Math.PI/2;
jack(-20,48.6,3.8,'Main / headphone output');
// Rear screws and feet are explicitly approximate rather than internal CAD.
for(const x of [-28,28])for(const z of [-40,40]){const o=obj(new T.CylinderGeometry(1.6,1.6,.4,16),black,[x,-.75,z],'Rear fastener','Approximate external screw placement.');}
scene.add(new T.HemisphereLight('#ffffff','#59666b',2));const light=new T.DirectionalLight('#ffffff',3);light.position.set(-50,120,70);scene.add(light);
let controls;if(renderer){renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;stage.append(renderer.domElement);$('loading').hidden=true;controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minZoom=.6;controls.maxZoom=4;controls.target.set(0,8,0)}
function view(){camera.up.set(0,1,0);const pos={iso:[120,155,145],front:[0,220,.01],side:[220,8,0],back:[0,-220,.01]}[$('view').value];if(['front','back'].includes($('view').value))camera.up.set(0,0,-1);camera.position.set(...pos);camera.lookAt(0,8,0);camera.zoom=1;camera.updateProjectionMatrix();controls?.update()}
function resize(){if(!renderer)return;const w=stage.clientWidth,h=stage.clientHeight,a=w/h;camera.left=-78*a;camera.right=78*a;camera.top=78;camera.bottom=-78;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}new ResizeObserver(resize).observe(stage);resize();view();
function action(key){if(key==='rec'||key==='memo'){state.mode=key==='memo'?'memo':'recording';state.time=0}else if(key==='play')state.mode=state.mode==='playing'?'paused':'playing';else if(key==='stop')state.mode='stopped';else if(key==='rew')state.time=Math.max(0,state.time-5);else if(key==='ff')state.time+=5;for(const b of moving)if(b.key===key){b.g.position.y=b.y-(reduced.matches?0:.8);setTimeout(()=>b.g.position.y=b.y,110)}document.querySelectorAll('.press').forEach(el=>el.classList.toggle('down',el.dataset.action===key));setTimeout(()=>document.querySelectorAll('.press.down').forEach(el=>el.classList.remove('down')),130);renderState()}
function format(){return String(Math.floor(state.time/60)).padStart(2,'0')+':'+String(Math.floor(state.time%60)).padStart(2,'0')}
let lastText='';function renderState(){const text=state.mode+' · '+format();$('read').textContent=text;$('plateRead').textContent=text;document.querySelectorAll('[data-action]').forEach(b=>{if(b.tagName==='BUTTON'&&['rec','play','stop'].includes(b.dataset.action))b.setAttribute('aria-pressed',String(({rec:'recording',play:'playing',stop:'stopped'})[b.dataset.action]===state.mode))});const t=document.querySelector('#iso .txt');if(t)t.textContent=format();if(text===lastText)return;lastText=text;const g=canvas.getContext('2d');g.fillStyle='#101412';g.fillRect(0,0,256,80);g.fillStyle='#eff3eb';g.font='20px monospace';g.fillText(state.mode.toUpperCase(),8,27);g.font='32px monospace';g.fillText(format(),8,65);screenTex.needsUpdate=true}
document.querySelectorAll('button[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));$('view').onchange=view;$('reset').onclick=view;$('wire').onclick=()=>{state.wire=!state.wire;$('wire').setAttribute('aria-pressed',String(state.wire));targets.forEach(o=>{o.userData.lines.visible=state.wire;o.material.transparent=state.wire;o.material.opacity=state.wire?.08:1})};$('theme').onclick=()=>{const light=document.documentElement.dataset.theme!=='light';document.documentElement.dataset.theme=light?'light':'dark';$('theme').textContent=light?'Dark theme':'Light theme'};
window.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.repeat||e.target.matches('select,input,textarea'))return;const key={r:'rec',p:'play',s:'stop'}[e.key.toLowerCase()];if(key){e.preventDefault();action(key)}});
if(renderer){const ray=new T.Raycaster(),pointer=new T.Vector2();let down=null;const node=renderer.domElement;node.addEventListener('pointerdown',e=>{if(e.isPrimary)down={id:e.pointerId,x:e.clientX,y:e.clientY}});node.addEventListener('pointercancel',()=>down=null);node.addEventListener('pointerup',e=>{if(!down||e.pointerId!==down.id)return;const d=down;down=null;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)>8)return;const r=node.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(targets,false)[0]?.object;if(hit){$('part').textContent=hit.userData.name+' — '+hit.userData.description;if(hit.userData.action)action(hit.userData.action)}})}
// iso-figure projection kernel: planar labels and non-scaling hairlines.
const C=Math.cos(Math.PI/6),S=Math.sin(Math.PI/6),OX=116,OY=31;
const P=(x,y,z)=>[(x-y)*C+OX,(x+y)*S-z+OY],D=(x,y,z)=>[(x-y)*C,(x+y)*S-z];
const plane=(O,U,V)=>{const o=P(...O),u=D(...U),v=D(...V);return 'matrix('+[u[0],u[1],v[0],v[1],o[0],o[1]].join(' ')+')'};
const TOP=(x,y,z)=>plane([x,y,z],[1,0,0],[0,1,0]),FRONT=(x,y,z)=>plane([x,y,z],[1,0,0],[0,0,-1]),SIDE=(x,y,z)=>plane([x,y,z],[0,-1,0],[0,0,-1]);
const rect=(t,w,h,r=0,cls='face')=>'<g transform="'+t+'"><rect class="'+cls+'" width="'+w+'" height="'+h+'" rx="'+r+'"/></g>';
const box=(x,y,z,w,d,h,r=0)=>rect(SIDE(x+w,y+d,z+h),d,h,Math.min(r,h/4))+rect(FRONT(x,y+d,z+h),w,h,Math.min(r,h/4))+rect(TOP(x,y,z+h),w,d,r,'face top');
let svg=box(0,0,0,68,96,16,3);svg+='<g transform="'+TOP(34,45,18)+'"><circle class="face top" r="25.7"/><circle class="detail" r="16.5"/><circle class="detail" r="8.2"/></g>';svg+=rect(TOP(15,5,16.8),29,9,1);svg+='<g transform="'+TOP(18,7,17)+'"><text class="txt" y="5">00:00</text></g>';
for(const [x,key,glyph]of[[6,'rec','●'],[26,'play','▶'],[46,'stop','■']])svg+='<g class="press" role="button" tabindex="0" aria-label="'+key+'" data-action="'+key+'">'+box(x,80,16,15,10,2,1.5)+'<g transform="'+TOP(x,80,18)+'"><text class="txt" x="5" y="7">'+glyph+'</text></g></g>';
$('iso').innerHTML=svg;$('iso').addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el)action(el.dataset.action)});$('iso').addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.dataset.action){e.preventDefault();action(e.target.dataset.action)}});
let last=performance.now();function loop(now){const dt=Math.min((now-last)/1000,.1);last=now;if(!document.hidden){if(['recording','playing','memo'].includes(state.mode)){state.time+=dt;if(!reduced.matches)wheel.rotation.y-=dt*.8}renderState();controls?.update();renderer?.render(scene,camera)}requestAnimationFrame(loop)}renderState();requestAnimationFrame(loop);
